---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration
  tasks:
  - meta: refresh_inventory

  - name: Create inventory folder
    file:
      state: directory
      path: "{{ekara_inventory_path}}"

  - name: Gather instances
    os_server_facts:
  - set_fact:
      ekara_instances: []
      ekara_workers: []
  - name: Filter nodes
    set_fact:
      ekara_instances: "{{ ekara_instances + [ item ] }}"
    with_items: "{{openstack_servers}}"
    when:
    - item.metadata.Stack_id is defined
    - item.metadata.Stack_id == ekara_configuration_params.environment.uid
    loop_control:
      label: "{{ item.name }}"
  - name: Gather Worker hosts
    set_fact:
      ekara_workers: "{{ ekara_workers + [ item ] }}"
    with_items: "{{ekara_instances}}"
    when:
    - item.metadata.Swarm_type is defined
    - item.metadata.Swarm_type == 'worker'
    loop_control:
      label: "{{ item.name }}"

  - name: Update local inventory
    template:
      src: templates/hosts.j2
      dest: "{{ekara_inventory_path}}/hosts"

  - name: Check IP configuration
    set_fact:
      ekara_public_ip: "{{ ekara_configuration_params.params.assign_public_ip | default(True) }}"
      ekara_ip: public_v4
  - name: Fix IP
    set_fact:
      ekara_ip: private_v4
    when:
    - ekara_public_ip == False
  - name: Add ssh configuration for each instance with proxy
    include_role:
      name: ekara.ssh
    vars:
      ekara_ssh_proxy: "{{ekara_configuration_params.proxy.http_proxy}}"
      ekara_ssh_key: "{{ ekara_configuration_params.connectionConfig.machine_private_key }}"
      ekara_ssh_host: "{{item[ekara_ip]}}"
    when:
    - ekara_configuration_params.proxy is defined
    with_items:
    - "{{ ekara_instances }}"
    loop_control:
      label: "{{ item.name }}"
  - name: Add ssh configuration for each instance without proxy
    include_role:
      name: ekara.ssh
    vars:
      ekara_ssh_proxy:
      ekara_ssh_key: "{{ ekara_configuration_params.connectionConfig.machine_private_key }}"
      ekara_ssh_host: "{{item[ekara_ip]}}"
    when:
    - ekara_configuration_params.proxy is not defined
    with_items:
    - "{{ ekara_instances }}"
    loop_control:
      label: "{{ item.name }}"
