---
- name: Set Stack name
  set_fact:
    ekara_stack_meta:
      ek.stack_name: "{{ekara_stack_name}}"
      ek.stack_id: "{{ekara_configuration_params.environment.id}}"
      ek.stack_qualifier: "{{ekara_configuration_params.environment.qualifier}}"
      ek.stack_nodeset: "{{ekara_configuration_params.environment.nodeset}}"
- name: Prepare metadata
  set_fact:
    ekara_os_metadata: "{{ ekara_configuration_params.params.metadata | default({})| combine(ekara_stack_meta) }}"
- name: Add labels into metadata
  set_fact:
    ekara_os_metadata: "{{ ekara_os_metadata | combine(ekara_configuration_params.labels) }}"
  when:
  - ekara_configuration_params.labels is defined

- name: Define default machines names
  set_fact:
    ekara_prefix_names: "{{ekara_configuration_params.params.prefix_names | default(ekara_stack_id)}}"
  when:
  - ekara_os_machine_names is not defined

- name: Generate template to create instances
  template:
    src: "templates/heats/{{item}}"
    dest: "{{ekara_temp_dir}}/{{item}}"
  with_items:
  - heat-stack.yaml
  - heat-server.yaml
  - heat-volume.yaml

- name: Create stack
  register: ekara_os_stack
  os_stack:
    name: "{{ekara_stack_id}}"
    state: present
    template: "{{ekara_temp_dir}}/heat-stack.yaml"
    parameters:
      names: "{{ekara_os_machine_names | default([])}}"
      node_count: "{{ekara_configuration_params.instances}}"
      key: "{{ ekara_keypair_name }}"
      image: "{{ ekara_configuration_params.params.image }}"
      flavor: "{{ ekara_configuration_params.params.flavor }}"
      private_network: "{{ ekara_configuration_params.params.private_network }}"
      public_network: "{{ ekara_configuration_params.params.public_network | default('')}}"
      dns_zone: "{{ekara_configuration_params.params.dns_zone | default('')}}"
      volumes: "{{ekara_configuration_params.volumes | default({}) | to_json }}"
      volumes_count: "{{ekara_configuration_params.volumes | default({}) | length }}"

- name: Add Swarms tags
  include_tasks: "tag-swarm.yml"
