- name: Generate template to create instances
  template:
    src: "templates/heats/{{item}}"
    dest: "{{lagoon_temp_dir}}/{{item}}"
  with_items:
  - heat-stack.yaml
  - heat-server.yaml
  - heat-volume.yaml

- name: create stack
  register: stack_create
  os_stack:
    name: "{{lagoon_configuration_params.environment.name}}_{{lagoon_configuration_params.environment.uid}}"
#    tag: "{{ tag_name }}"
    state: present
    template: "{{lagoon_temp_dir}}/heat-stack.yaml"
    parameters:
      names: "{{lagoon_os_machine_names | default({})}}"
      node_count: "{{lagoon_configuration_params.instances}}"
      key: "{{ lagoon_keypair_name }}"
      image: "{{ lagoon_configuration_params.params.image }}"
      flavor: "{{ lagoon_configuration_params.params.flavor }}"
      private_network: "{{ lagoon_configuration_params.params.private_network }}"
      public_network: "{{ lagoon_configuration_params.params.public_network | default('')}}"
      availability_zone: "{{ lagoon_configuration_params.params.availability_zone | default('') }}"
#      secgroups: "{{lagoon_configuration_params.params.security_groups}}"
      dns_zone: "{{lagoon_configuration_params.params.dns_zone | default('')}}"
      volumes: "{{lagoon_configuration_params.volumes | default({}) | to_json }}"
      volumes_count: "{{lagoon_configuration_params.volumes | default({}) | length }}"
#        disk_docker_size: "{{ disks.docker.size }}"
#        disk_users_size: "{{ disks.users.size }}"
#        caas_platform_name: "{{ cmdb.caas.platform }}"
#        iaas_platform_name: "{{ cmdb.iaas.platform }}"
#        caas_space_name: "{{ cmdb.caas.space }}"
#        iaas_space_name: "{{ cmdb.iaas.space }}"
- debug: var=stack_create
        