---
- name: List volumes
  set_fact:
    volumes:
    - name: "{{ ekara_os_stack.stack.outputs[1].output_value[my_idx] }}"
      volumes: "{{ ekara_os_stack.stack.outputs[3].output_value[my_idx]}}"
      devices: "{{ ekara_os_stack.stack.outputs[2].output_value[my_idx] }}"
  loop: "{{ ekara_os_stack.stack.outputs[1].output_value}}"
  loop_control:
    index_var: my_idx
  register: ekara_os_volumes
