heat_template_version: 2016-04-08

description: >
  Node template to create a volumes for a server.
  
parameters:
  indexv:
    type: number
    
  volume_params:
    type: json
    
  instance_id:
    type: string
    description: Server to attach volume to
  instance_name:
    type: string
    description: Server name

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      size: {  get_param: [ volume_params , {get_param: indexv} , "params" , "volume_size" ] }
      volume_type: {  get_param: [ volume_params , {get_param: indexv} , "params" , "volume_type" ] }
      description:
        str_replace:
          template: Volume for stack ${INSTANCE} - ${NAME}
          params:
            ${INSTANCE}: { get_param: "instance_name" }
            ${NAME}: {  get_param: [ volume_params , {get_param: indexv} , "path" ] }
      name:
        str_replace:
          template: ${INSTANCE}-${INDEX}
          params:
            ${INSTANCE}: { get_param: "instance_name" }
            ${NAME}: {  get_param: [ volume_params , {get_param: indexv} , "path" ] }
            ${INDEX}: { get_param: indexv }

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_param: instance_id }

outputs:
  volume_id:
    value: {get_resource: volume_attachment}
  volume_name:
    value: { get_param: [ volume_params , {get_param: indexv} , "path" ] }
    