heat_template_version: 2016-04-08

description: >
  Node template to create a volumes for a server.
  
parameters:
  instance_id:
    type: string
    description: Server to attach volume to
  instance_name:
    type: string
    description: Server name

resources:

# {% if ekara_configuration_params.volumes is defined %} Create volumes
# {% for v in ekara_configuration_params.volumes %} Volume {{v.path}}
  volume{{v.path|replace('/','_')}}:
    type: OS::Cinder::Volume
    properties:
      size: {{v.params.volume_size}}
      volume_type: {{v.params.volume_type}}
      description:
        str_replace:
          template: ${INSTANCE} ${NAME}
          params:
            ${INSTANCE}: { get_param: "instance_name" }
            ${NAME}: "{{v.path}}"

  volume_attachment{{v.path|replace('/','_')}}:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: "volume{{v.path|replace('/','_')}}" }
      instance_uuid: { get_param: instance_id }
# {% endfor %}{% endif %}

outputs:
  volume_id: 
    value: 
# {% for v in ekara_configuration_params.volumes %} Volume id
    - {get_resource: "volume_attachment{{v.path|replace('/','_')}}"}
# {% endfor %}

  volume_name: 
    value: 
# {% for v in ekara_configuration_params.volumes %} Volume Path
    - {{v.path}}
# {% endfor %}
    