heat_template_version: 2016-04-08

description: >
  Node template to create a server.

parameters:
  index:
    type: number
    description: Number of the server
  names:
    type: comma_delimited_list
    description: Names of the server
  stack_name:
    type: string
    description: Name of the stack
  key:
    type: string
    description: Name of keypair to assign to server
  image:
    type: string
    description: Name of image to use for servers
  flavor:
    type: string
    description: Flavor to use for server
  availability_zone:
    type: string
    description: Availability zone for server
    default: nova
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
  public_network:
    type: string
    label: Public network name or ID
    description: Network to attach instance to.
  dns_zone:
    type: string
    description: DNS zone for server
  volumes:
    type: json
  volumes_count:
    type: number


resources:

{% if lagoon_configuration_params.params.public_network is defined %}
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: public_network }
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: instance }
{% endif %}

{% if lagoon_configuration_params.params.dns_zone is defined %}
  instancerecord:
    type: OS::Designate::Record
    properties:
      name: { list_join: ['.', [{ get_attr: [instance, name] }, { get_param: dns_zone }]] }
      data: { get_attr: [instance, first_address] }
      description: { get_attr: [instance, name] }
      domain: { get_param: dns_zone }
      type: "A"
{% endif %}

  group_of_volumes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: volumes_count }
      resource_def:
        type: heat-volume.yaml
        properties:
          instance_id: { get_resource: instance }
          instance_name: { get_attr: [instance, name]  }
          volume_params: { get_param: volumes }
          indexv: '%index%'

  instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
{% if lagoon_configuration_params.params.availability_zone is defined %}      availability_zone : {{lagoon_configuration_params.params.availability_zone }}
{% endif %}
      key_name: { get_param: key }
{% if lagoon_os_machine_names is defined %}
      name:
        str_replace:
          template: ${NAME}
          params:
            ${NAME}: { get_param: [ names , get_param: index ] }
{% else %}
      name:
        str_replace:
          template: ${STACK}-${INDEX}
          params:
            ${INDEX}: { get_param: index }
            ${STACK}: { get_param: stack_name }
{% endif %}
{% if lagoon_configuration_params.params.security_groups is defined %}      security_groups: 
{% for sec in lagoon_configuration_params.params.security_groups %}
      - {{ sec}}
{% endfor %}
{% endif %}
      networks:
        - network: { get_param: private_network }
{% if lagoon_configuration_params.params.user_data is defined %}
      user_data_format: RAW
      user_data: |
{{ lagoon_configuration_params.params.user_data | indent(8,true) }}
{% endif %}
{% if lagoon_configuration_params.params.metadata is defined %}      metadata:
{{ lagoon_configuration_params.params.metadata | to_nice_yaml | indent(8,true)}}
{% endif %}
#      block_device_mapping:
#        - device_name: vde
#          volume_id: noreflex-0-1
#          delete_on_termination: true