heat_template_version: 2016-04-08

description: >
  Node template to create a volumes for a server.
  
parameters:
  index:
    type: number
    
  volume_params:
    type: json
    
  instance_id:
    type: string
    description: Server to attach volume to
  instance_name:
    type: string
    description: Server name

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      size: {  get_param: [ volume_params , {get_param: index} , "params" , "volume_size" ] }
      volume_type: {  get_param: [ volume_params , {get_param: index} , "params" , "volume_type" ] }
      description:
        str_replace:
          template: Volume for stack ${NAME}
          params:
            ${NAME}: { get_param: "instance_name" }
      name:
        str_replace:
          template: ${INSTANCE}-${NAME}
          params:
            ${INSTANCE}: { get_param: "instance_name" }
            ${NAME}: {  get_param: [ volume_params , {get_param: index} , "name" ] }
      

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_param: instance_id }
      mountpoint: {  get_param: [ volume_params , {get_param: index} , "params" , "device_name" ] }